### ISSUE TITLE
Police Job features

### ISSUE THREAD

**Issue by andslasher123** [FiveM-Scripts/es_freeroam#19]
I have some suggestions of how the police job should be whenever you guys start working on it. Basically, when becoming police there be an NPC and a marker at mission row to become police which will automatically switch to the cop skin. To change the cop skin appearance, the player needs to go to the locker room and change their clothing and appearance whatever they like. This as well is given all the weapons needed when going on duty. There should be also a weapon GUI menu where players can spend money on ammo on their police weapons, Of course, this will be done at the weapon room at mission row. Now while on duty there be numerous of features available to him such as handcuffing, giving fines, place a person wanted and jailing. There would be also a voice chat system and text system, specifically for cops and also EMS/Fire. How the voice chat system would work is basically a radio where players can talk while being on a channel similar to what fivereborn menu voice system is and players can switch the radio to local voice chat whenever they feel like with a push of a button or using a command like VoIP. Thats all the features I think we would work if u guys make the police job if I think anything else I update it.

**Comment by andslasher123** [comment]
2) Oh yeah, other great features for the police job would be running plates, an advanced backup system where officers can call backup and shows a location where they are by using a command /backup and shows on the map where they are similar to the outlaw script. Have spike strips available to them and I forget to mention this. Getting any police car from the mission row garage.

**Comment by Kerstern** [comment]
- Be able to call 911 and set a blip for cops directly to the player
- cops could open a menu and select different options :

1. Get ID infos (job, name, licences)
2. Take back items (weapons, drugs, alcohol etc)
3. Cuff
4. Fine
5. Get into car
6. Get in jail

**Comment by ghermans** [comment]
These suggestions will not be integrated in es_freeroam,   
However i added the above suggestions to another project that we are working on.
