### ISSUE TITLE
Vehicle Shop is Empty

### ISSUE THREAD

**Issue by plysken** [FiveM-Scripts/es_freeroam#3]
Hi, 

Vehicle Shop is Empty, and i can pass trough it to fall under the map.

I think i'am missing something, could you help?

**Comment by ghermans** [comment]
I just installed a clean server with es_freeroam but i could not replicate your issue.
Are you sure that you use the latest version from our github master branch?

below are some screenshots fyi.

![20170414201622_1](https://cloud.githubusercontent.com/assets/1594411/25051916/5a9ae2a6-214f-11e7-9127-523e06889598.jpg)

![20170414201639_1](https://cloud.githubusercontent.com/assets/1594411/25051917/5aa04e12-214f-11e7-9a33-0dcfc37e6951.jpg)

**Comment by plysken** [comment]
Yes, but i m going to do it another time whit a fresh fresh server and all you file from here.

2 Another thing : 
1 - https://github.com/FiveM-Scripts/Essential_Freeroam/archive/master.zip is broken im your main page a point 1

2 - I make a garage scrip base on vehshop code, i want to contribuate to es_freeroam, how i can send you.
(my script is not perfect but it's kind of something)

**Comment by FiveM-Sith** [comment]
(2) If you'd like to submit it, fork our project es_freeroam and push the resource and then inform us here. 😃

**Comment by plysken** [comment]
ok it's done
https://github.com/plysken/Garages
