### ISSUE TITLE
The server wont spawn players (es_freeroam 0.1.3)

### ISSUE THREAD

**Issue by AODeltaB** [FiveM-Scripts/es_freeroam#36]
![image](https://cloud.githubusercontent.com/assets/18491516/24852528/23ef6116-1dd8-11e7-826a-fd7411722473.png)
I got this error when someone join my server, the spawnpoint is set, i'have nomore errors in log.

**Comment by ghermans** [comment]
Did you do a clean install or did you upgrade from the previous versions?

**Comment by AODeltaB** [comment]
I did a clean install, and did (after) a upgrade

**Comment by AODeltaB** [comment]
I did another upgrade but same error, i do not understand, i disabled other scripts but still nothing :/ :(

**Comment by ghermans** [comment]
If other testers report an issue for it, then i will label the issue as a bug.

**Comment by ImChiip** [comment]
same error on a clean install 
http://image.prntscr.com/image/07b078ff06e447bca59aeddeab11ec81.jpeg
AutoStartResources:
    - chat
    - spawnmanager
    - essentialmode
    - es_admin
    - es_freeroam
    - imchip-map-gtav
    - baseevents
    - rconlog
    - hardcap
    - scoreboard
    - keks

**Comment by ghermans** [comment]
https://github.com/FiveM-Scripts/es_freeroam/blob/master/config.lua#L10 <= are these set in your config.lua?

**Comment by ImChiip** [comment]
for me yes

**Comment by AODeltaB** [comment]
Yes same !

**Comment by ghermans** [comment]
Only thing i can suggest atm is try this AutoStartResources in your citmp-server.yml

    - chat
    - spawnmanager
    - essentialmode
    - es_freeroam
    - es_admin
    - fivem-map-hipster
    - rconlog
    - hardcap
    - baseevents
    - rconlog
    - hardcap # prevents too many players from joining

**Comment by puccino** [comment]
It did not fix the issue for me

**Comment by ghermans** [comment]
Can you all download the resource again? normally this should be fixed now

**Comment by Ankor12** [comment]
Great job, its working with your fix

**Comment by ImChiip** [comment]
Worked for me
